import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import TopProgress from "@/components/shared/TopProgress";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "sonner";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Suspense fallback={null}>
            <TopProgress />
          </Suspense>
          <Suspense fallback={null}>
            <Navbar />
          </Suspense>
          <div className="min-h-screen">
            <Suspense fallback={
              <div className="min-h-screen flex items-center justify-center">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
              </div>
            }>
              {children}
            </Suspense>
          </div>
          <Toaster position="top-right" />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}